[workspace]
members = ["yew-interop", "yew-interop-macro", "example", "yew-interop-core"]

# patch for stylist in the example crate
[patch.crates-io]
yew = {git = "https://github.com/yewstack/yew.git", branch="master"}
