[config]
default_to_workspace = false

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.check-example]
toolchain = "stable"
category = "checks"
command = "cargo"
args = ["clippy", "-p", "example"]


[tasks.check-yew-interop]
toolchain = "stable"
category = "checks"
command = "cargo"
args = ["clippy", "-p", "yew-interop", "--features", "yew-stable"]

[tasks.check-yew-interop-next]
toolchain = "stable"
category = "checks"
command = "cargo"
args = ["clippy", "-p", "yew-interop", "--features", "yew-next"]

[tasks.lint]
toolchain = "stable"
category = "checks"
command = "cargo"
args = ["fmt", "--all", "--" ,"--check"]
