[package]
name = "yew-interop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gloo-events = "0.1"
wasm-bindgen = "0.2"
yew = "0.19.3"
gloo-utils = "0.1"
yew-interop-core = {path = "../yew-interop-core" }
yew-interop-macro = {path = "../yew-interop-macro" }

[dependencies.web-sys]
version = "0.3"
features = [
    "HtmlHeadElement",
    "HtmlLinkElement",
    "HtmlScriptElement"
]