[package]
name = "yew-interop"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "use javascript and css asynchrously in yew"
homepage = "https://github.com/Madoshakalaka/yew-interop"
repository = "https://github.com/Madoshakalaka/yew-interop"
readme = "../README.md"

keywords = ["yew", "interop", "js", "css", "npm"]
categories = ["api-bindings", "asynchronous", "wasm", "web-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gloo-events = "0.1"
wasm-bindgen = "0.2"
yew = {git="https://github.com/yewstack/yew.git", branch="master"}
gloo-utils = "0.1"
yew-interop-core = {path = "../yew-interop-core" }
yew-interop-macro = {path = "../yew-interop-macro" }

[dependencies.web-sys]
version = "0.3"
features = [
    "HtmlHeadElement",
    "HtmlLinkElement",
    "HtmlScriptElement"
]