name: Checks for dev-tool

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'dev-tool/**'
  push:
    branches: [ master ]
    paths:
      - 'dev-tool/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: clippy
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-${{ runner.os }}-clippy-dev-tool-${{hashFiles('Cargo.lock')}}
          restore-keys: |
            cargo-${{ runner.os }}-clippy-dev-tool
            cargo-${{ runner.os }}
      - name: Timestamp Cached Target
        run: ./dev-tool/ci-bin/cargo-sweep sweep -s
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -p dev-tool
      - name: Remove Untouched Cache
        run: ./dev-tool/ci-bin/cargo-sweep sweep -f

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-${{ runner.os }}-test-dev-tool-${{hashFiles('Cargo.lock')}}
          restore-keys: |
            cargo-${{ runner.os }}-test-dev-tool
            cargo-${{ runner.os }}
      - name: Timestamp Cached Target
        run: ./dev-tool/ci-bin/cargo-sweep sweep -s
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p dev-tool
      - name: Remove Untouched Cache
        run: ./dev-tool/ci-bin/cargo-sweep sweep -f
