name: "Publish a Versioned Demo Website"

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: A semver version like 1.2.3
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  publish-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          target: wasm32-unknown-unknown

      - uses: jetli/trunk-action@v0.1.0
        with:
          version: 'latest'

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -p dev-tool --bin build-demo -- ${{ github.event.inputs.version }}

      - run: git pull

      - name: Commit the Binary
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "🤖 build demo website for ${{ github.event.inputs.version }}"
