name: Checks with Yew's master Branch

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'yew-interop/**'
      - 'yew-interop-core/**'
      - 'yew-interop-macro/**'
  push:
    branches: [ master ]
    paths:
      - 'yew-interop/**'
      - 'yew-interop-core/**'
      - 'yew-interop-macro/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  test-yew-interop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-${{ runner.os }}-test-yew-interop-next-${{hashFiles('Cargo.lock')}}
          restore-keys: |
            cargo-${{ runner.os }}-test-yew-interop-next
            cargo-${{ runner.os }}
      - name: Timestamp Cached Target
        run: ./dev-tool/ci-bin/cargo-sweep sweep -s
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p yew-interop --features yew-next
      - name: Remove Untouched Cache
        run: ./dev-tool/ci-bin/cargo-sweep sweep -f

  test-yew-interop-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-${{ runner.os }}-test-yew-interop-next-script-${{hashFiles('Cargo.lock')}}
          restore-keys: |
            cargo-${{ runner.os }}-test-yew-interop-next-script
            cargo-${{ runner.os }}
      - name: Timestamp Cached Target
        run: ./dev-tool/ci-bin/cargo-sweep sweep -s
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p yew-interop --features yew-next --features script
      - name: Remove Untouched Cache
        run: ./dev-tool/ci-bin/cargo-sweep sweep -f

  clippy-yew-interop-macro:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            dependencies:
              - 'yew-interop-macro/**'
              - 'yew-interop-core/**'
      - uses: actions-rs/toolchain@v1
        if: steps.changes.outputs.dependencies == 'true'
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: clippy
      - uses: actions/cache@v2
        if: steps.changes.outputs.dependencies == 'true'
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-${{ runner.os }}-clippy-yew-interop-macro-next-${{hashFiles('Cargo.lock')}}
          restore-keys: |
            cargo-${{ runner.os }}-clippy-yew-interop-macro-next
            cargo-${{ runner.os }}
      - name: Timestamp Cached Target
        if: steps.changes.outputs.dependencies == 'true'
        run: ./dev-tool/ci-bin/cargo-sweep sweep -s
      - name: Run clippy
        if: steps.changes.outputs.dependencies == 'true'
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -p yew-interop-macro --features yew-next -- -D warnings
      - name: Remove Untouched Cache
        if: steps.changes.outputs.dependencies == 'true'
        run: ./dev-tool/ci-bin/cargo-sweep sweep -f
  test-yew-interop-macro:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            dependencies:
              - 'yew-interop-macro/**'
              - 'yew-interop-core/**'
      - uses: actions-rs/toolchain@v1
        if: steps.changes.outputs.dependencies == 'true'
        with:
          toolchain: stable
          override: true
          profile: minimal
      - uses: actions/cache@v2
        if: steps.changes.outputs.dependencies == 'true'
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-${{ runner.os }}-test-yew-interop-macro-next-${{hashFiles('Cargo.lock')}}
          restore-keys: |
            cargo-${{ runner.os }}-test-yew-interop-macro-next
            cargo-${{ runner.os }}
      - name: Timestamp Cached Target
        if: steps.changes.outputs.dependencies == 'true'
        run: ./dev-tool/ci-bin/cargo-sweep sweep -s
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p yew-interop-macro --features yew-next
      - name: Remove Untouched Cache
        if: steps.changes.outputs.dependencies == 'true'
        run: ./dev-tool/ci-bin/cargo-sweep sweep -f
  test-yew-interop-macro-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            yew-interop-macro:
              - 'yew-interop-macro/**'
              - 'yew-interop-core/**'
      - uses: actions-rs/toolchain@v1
        if: steps.changes.outputs.dependencies == 'true'
        with:
          toolchain: stable
          override: true
          profile: minimal
      - uses: actions/cache@v2
        if: steps.changes.outputs.dependencies == 'true'
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-${{ runner.os }}-test-yew-interop-macro-next-script-${{hashFiles('Cargo.lock')}}
          restore-keys: |
            cargo-${{ runner.os }}-test-yew-interop-macro-next-script
            cargo-${{ runner.os }}
      - name: Timestamp Cached Target
        if: steps.changes.outputs.dependencies == 'true'
        run: ./dev-tool/ci-bin/cargo-sweep sweep -s
      - name: Run tests
        if: steps.changes.outputs.dependencies == 'true'
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p yew-interop-macro --features yew-next --features script
      - name: Remove Untouched Cache
        if: steps.changes.outputs.dependencies == 'true'
        run: ./dev-tool/ci-bin/cargo-sweep sweep -f
  clippy-yew-interop-macro-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            dependencies:
              - 'yew-interop-macro/**'
              - 'yew-interop-core/**'
      - uses: actions-rs/toolchain@v1
        if: steps.changes.outputs.dependencies == 'true'
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: clippy
      - uses: actions/cache@v2
        if: steps.changes.outputs.dependencies == 'true'
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-${{ runner.os }}-clippy-yew-interop-macro-next-script-${{hashFiles('Cargo.lock')}}
          restore-keys: |
            cargo-${{ runner.os }}-clippy-yew-interop-macro-next-script
            cargo-${{ runner.os }}
      - name: Timestamp Cached Target
        if: steps.changes.outputs.dependencies == 'true'
        run: ./dev-tool/ci-bin/cargo-sweep sweep -s

      - name: Run clippy
        if: steps.changes.outputs.dependencies == 'true'
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -p yew-interop-macro --features yew-next --features script -- -D warnings

      - name: Remove Untouched Cache
        if: steps.changes.outputs.dependencies == 'true'
        run: ./dev-tool/ci-bin/cargo-sweep sweep -f
  clippy-yew-interop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: clippy
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-${{ runner.os }}-clippy-yew-interop-next-${{hashFiles('Cargo.lock')}}
          restore-keys: |
            cargo-${{ runner.os }}-clippy-yew-interop-next
            cargo-${{ runner.os }}

      - name: Timestamp Cached Target
        run: ./dev-tool/ci-bin/cargo-sweep sweep -s

      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -p yew-interop --features yew-next -- -D warnings

      - name: Remove Untouched Cache
        run: ./dev-tool/ci-bin/cargo-sweep sweep -f

  clippy-yew-interop-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: clippy
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-${{ runner.os }}-clippy-yew-interop-next-script-${{hashFiles('Cargo.lock')}}
          restore-keys: |
            cargo-${{ runner.os }}-clippy-yew-interop-next-script
            cargo-${{ runner.os }}

      - name: Timestamp Cached Target
        run: ./dev-tool/ci-bin/cargo-sweep sweep -s

      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -p yew-interop --features yew-next --features script -- -D warnings

      - name: Remove Untouched Cache
        run: ./dev-tool/ci-bin/cargo-sweep sweep -f
