name: Checks with Yew's master Branch

on:
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/yew-next-pr.yml'
      - 'yew-interop/**'
      - 'yew-interop-core/**'
      - 'yew-interop-macro/**'
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/yew-next-pr.yml'
      - 'yew-interop/**'
      - 'yew-interop-core/**'
      - 'yew-interop-macro/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  test-yew-interop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - uses: Swatinem/rust-cache@v1


      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p yew-interop --features yew-next


  test-yew-interop-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - uses: Swatinem/rust-cache@v1


      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p yew-interop --features yew-next --features script


  clippy-yew-interop-macro:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            dependencies:
              - 'yew-interop-macro/**'
              - 'yew-interop-core/**'
      - uses: actions-rs/toolchain@v1
        if: steps.changes.outputs.dependencies == 'true'
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: clippy

      - uses: Swatinem/rust-cache@v1
        if: steps.changes.outputs.dependencies == 'true'

      - name: Run clippy
        if: steps.changes.outputs.dependencies == 'true'
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -p yew-interop-macro --features yew-next -- -D warnings
  clippy-yew-interop-macro-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            dependencies:
              - 'yew-interop-macro/**'
              - 'yew-interop-core/**'
      - uses: actions-rs/toolchain@v1
        if: steps.changes.outputs.dependencies == 'true'
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: clippy

      - uses: Swatinem/rust-cache@v1
        if: steps.changes.outputs.dependencies == 'true'


      - name: Run clippy
        if: steps.changes.outputs.dependencies == 'true'
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -p yew-interop-macro --features yew-next --features script -- -D warnings

  clippy-yew-interop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: clippy

      - uses: Swatinem/rust-cache@v1



      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -p yew-interop --features yew-next -- -D warnings



  clippy-yew-interop-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: clippy

      - uses: Swatinem/rust-cache@v1



      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -p yew-interop --features yew-next --features script -- -D warnings


