name: Checks with Yew's master Branch

on:
  schedule:
    # every day at 9
    - cron: '0 9 * * *'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy-integration:
    runs-on: ubuntu-latest

    steps:    
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: clippy
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-${{ runner.os }}-clippy-integration-yew-next-${{hashFiles('Cargo.lock')}}
          restore-keys: |
            cargo-${{ runner.os }}-clippy-integration-yew-next
            cargo-${{ runner.os }}

      - name: Timestamp Cached Target
        run: ./dev-tool/ci-bin/cargo-sweep sweep -s

      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -p integration-test --features yew-next -- -D warnings

      - name: Remove Untouched Cache
        run: ./dev-tool/ci-bin/cargo-sweep sweep -f

  clippy-integration-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: clippy
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-${{ runner.os }}-clippy-integration-yew-next-script-${{hashFiles('Cargo.lock')}}
          restore-keys: |
            cargo-${{ runner.os }}-clippy-integration-yew-next
            cargo-${{ runner.os }}

      - name: Timestamp Cached Target
        run: ./dev-tool/ci-bin/cargo-sweep sweep -s

      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -p integration-test --features yew-next --features script -- -D warnings

      - name: Remove Untouched Cache
        run: ./dev-tool/ci-bin/cargo-sweep sweep -f
