name: "Cron: Checks with Yew's master Branch"

on:
  schedule:
    # every day at 9
    - cron: '0 9 * * *'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test-yew-interop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - uses: Swatinem/rust-cache@v1

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p yew-interop --features yew-next


  test-yew-interop-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - uses: Swatinem/rust-cache@v1


      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p yew-interop --features yew-next --features script


  clippy-yew-interop-macro:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: clippy

      - uses: Swatinem/rust-cache@v1


      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -p yew-interop-macro --features yew-next --all-targets -- -D warnings

  clippy-yew-interop-macro-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        if: steps.changes.outputs.yew-interop-macro == 'true'
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: clippy

      - uses: Swatinem/rust-cache@v1



      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -p yew-interop-macro --features yew-next --features script --all-targets -- -D warnings


  clippy-yew-interop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: clippy

      - uses: Swatinem/rust-cache@v1



      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -p yew-interop --features yew-next --all-targets -- -D warnings



  clippy-yew-interop-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: clippy

      - uses: Swatinem/rust-cache@v1



      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -p yew-interop --features yew-next --features script --all-targets -- -D warnings


